/**
 * Provides functionality for the settings page.
 *
 * @namespace
 */
var settings = {};

/**
 * @summary Form for updating an account's password.
 *
 * @class
 * @augments Form
 */
settings.PasswordForm = function()
{
	Form.call(this, '#PasswordForm');

	/**
	 * Alias to the class level `this`.
	 *
	 * @type {settings.PasswordForm}
	 */
	var _this = this;

	/**
	 * Button which submits this form.
	 *
	 * @type {Button}
	 */
	var _submitButton = new Button('#PasswordForm_SubmitButton');

	/**
	 * Submits this form.
	 */
	function onSubmit(e) {
		Form.PreventDefault(e);
		if (_this.HasErrors())
			return;
		_submitButton.SetLoading(true);
		gModel.UpdatePassword(
			_this.GetSubmitString(),
			function(message) { gController.ShowSuccess(message); },
			function() { _submitButton.SetLoading(false); }
		);
	}

	this.OnSubmit(onSubmit);
}

Element.Inherit(settings.PasswordForm, Form);

/**
 * @summary Manages communication with the server.
 *
 * @class
 * @augments AppModel
 */
settings.Model = function()
{
	AppModel.call(this);

	/**
	 * Updates an account's password with a new one.
	 *
	 * @param data {string} Form data which is generated by {@link settings.PasswordForm}.
	 * It contains the following fields:
	 *   * PasswordToken
	 *   * Password
	 *   * NewPassword
	 * @param onSuccess {function} Function to call on success.
	 * @param onComplete {function} Function to call on complete.
	 */
	this.UpdatePassword = function(data, onSuccess, onComplete) {
		this.Post(Model.ActionURL('UpdatePassword'), data, onSuccess, onComplete);
	}
}

Element.Inherit(settings.Model, AppModel);

/**
 * @summary Manages the components on the page.
 *
 * @class
 * @augments AppController
 */
settings.Controller = function()
{
	AppController.call(this);

	/**
	 * Form for updating an account's password.
	 *
	 * @type {settings.PasswordForm}
	 */
	var _passwordForm = new settings.PasswordForm();
}

Element.Inherit(settings.Controller, AppController);

/**
 * The global model object.
 *
 * @global
 * @type {settings.Model}
 */
var gModel;

/**
 * The global controller object.
 *
 * @global
 * @type {settings.Controller}
 */
var gController;

$(document).ready(function()
{
	gModel = new settings.Model();
	gController = new settings.Controller();
});
